<a href="https://colab.research.google.com/github/aeishugupta/Learning_journey/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is Pandas?
Pandas is an open-source Python library for fast, flexible, and efficient data manipulation and analysis.
Pandas is a free, open-source Python library used extensively for data manipulation and analysis. It acts like a highly programmable, supercharged version of Microsoft Excel or SQL within Python, allowing developers and data scientists to easily clean, filter, reshape, and analyze structured data.

# Why Pandas?
Easy handling of tabular data. Fast data processing. Built-in data cleaning tools. Powerful grouping and aggregation supports.

# Applications
Data Cleaning, Data Wrangling, Business Intelligence, Finance Analytics, Healthcare Analytics, Machine Learning , Data Visualization

In [ ]:
#import pandas
import pandas as pd
import numpy as np

print(pd.__version__)

2.2.3

In [ ]:
#Series with custom index
marks = pd.Series(
    [85,90,78],
    index = ['A','B','C']
)
print(marks)

A    85
B    90
C    78
dtype: int64

In [ ]:
#Access Elements
marks['A']

np.int64(85)

In [ ]:
# Data Frame
# Create DataFrame
data = {
    'Name' : ['Alice','Bob','Charlie'],
    'Age' : [21,20,19],
    'Marks' : [85,92,88]
}

df = pd.DataFrame(data)
print(df)

      Name  Age  Marks
0    Alice   21     85
1      Bob   20     92
2  Charlie   19     88

In [ ]:
#View Data
df.head()
df.tail()
df.sample(2)

    Name  Age  Marks
1    Bob   20     92
0  Alice   21     85

In [ ]:
# Shape
df.shape

(3, 3)

In [ ]:
# Columns
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [ ]:
# Data Types
df.dtypes

Name     object
Age       int64
Marks     int64
dtype: object

In [ ]:
#Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [ ]:
#Module 3
# Loading Data
# CSV File
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/people-100.csv')
df.head()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon

In [ ]:
df= pd.read_csv('/content/sample_data/california_housing_test.csv',index_col=0)
df.head()

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
longitude,,,,,,,,
-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3000 entries, -122.05 to -119.63
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   latitude            3000 non-null   float64
 1   housing_median_age  3000 non-null   float64
 2   total_rooms         3000 non-null   float64
 3   total_bedrooms      3000 non-null   float64
 4   population          3000 non-null   float64
 5   households          3000 non-null   float64
 6   median_income       3000 non-null   float64
 7   median_house_value  3000 non-null   float64
dtypes: float64(8)
memory usage: 210.9 KB

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Module 5
# GroupBy
# Example
data = {
    'Department':['CSE','ECE','CSE','IT','ECE'],
    'Salary':[50000,60000,55000,70000,65000]
}

df = pd.DataFrame(data)
print(df)

  Department  Salary
0        CSE   50000
1        ECE   60000
2        CSE   55000
3         IT   70000
4        ECE   65000

In [ ]:
#Average Salary
df.groupby('Department')['Salary'].mean()

Department
CSE    52500.0
ECE    62500.0
IT     70000.0
Name: Salary, dtype: float64

In [ ]:
#Count
df.groupby('Department')['Salary'].count()

Department
CSE    2
ECE    2
IT     1
Name: Salary, dtype: int64

In [ ]:
#Maximum
df.groupby('Department')['Salary'].max()

Department
CSE    55000
ECE    65000
IT     70000
Name: Salary, dtype: int64

In [ ]:
#Multiple Aggregation
df.groupby('Department')['Salary'].agg(['mean','max','min','count'])

               mean    max    min  count
Department
CSE         52500.0  55000  50000      2
ECE         62500.0  65000  60000      2
IT          70000.0  70000  70000      1

In [ ]:
Student = pd.DataFrame({
    'ID':[1,2,3],
    'Name':['Alice','Bob','Charlie'],
    'Age':[21,20,19]
})

In [ ]:
Marks = pd.DataFrame({
    'ID':[1,2,3],
    'Subject':['Math','Science','English'],
    'Marks':[90,85,92]
})

In [ ]:
merged = pd.merge(Student,Marks,on='ID')
print(merged)

   ID     Name  Age  Subject  Marks
0   1    Alice   21     Math     90
1   2      Bob   20  Science     85
2   3  Charlie   19  English     92

In [ ]:
# Concatenate
pd.concat(
    [Student,Marks]
    ,axis=1)

   ID     Name  Age  ID  Subject  Marks
0   1    Alice   21   1     Math     90
1   2      Bob   20   2  Science     85
2   3  Charlie   19   3  English     92

In [ ]:
# Pivot table
pd.pivot_table(
    df,
    values='Salary',
    index='Department',
    aggfunc='mean'
)

             Salary
Department
CSE         52500.0
ECE         62500.0
IT          70000.0

Mini Projects:

Tasks:

Load DataSet

Display first five rows

Dataset information

Summary statistics

Check missing values

remove duplicates

Filter houses with median income > 5

Create a new column (Income * 2 )

Sort by house value

In [ ]:
# DataSet Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Department  5 non-null      object
 1   Salary      5 non-null      int64
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

In [ ]:
#Display first five rows
df.head(5)

  Department  Salary
0        CSE   50000
1        ECE   60000
2        CSE   55000
3         IT   70000
4        ECE   65000

In [ ]:
#Summary statistics
print(df.describe())

            Salary
count      5.00000
mean   60000.00000
std     7905.69415
min    50000.00000
25%    55000.00000
50%    60000.00000
75%    65000.00000
max    70000.00000

In [ ]:
#Check missing values
print(df.isna().sum())

Department    0
Salary        0
dtype: int64

In [ ]:
#remove duplicates
df = df.drop_duplicates()

In [ ]:
#Filter houses with median income > 5
df_filtered = df[df['median_income'] > 5]
print(df_filtered)

KeyError: 'median_income'

In [ ]:
#Create a new column (Income * 2 )
df_filtered['income_doubled'] = df_filtered['median_income'] * 2

In [ ]:
#Sort by house value
df_final = df_filtered.sort_values(by='median_house_value', ascending=True)
print(df_final)

In [ ]:
# Display top 10 records
top_10_records = df.head(10)
print(top_10_records)

In [ ]:
# Compute average income
average_income = df['median_income'].mean()
print("Average Income:", average_income)